import pandas as pd

def deduplicate(df: pd.DataFrame) -> pd.DataFrame:
    """
    Remove overlapping records generated by scraping the same active listing
    across consecutive days. Retain only the most recent observation per unique listing ID.
    """
    if "last_seen" in df.columns:
        df = df.sort_values(by="last_seen", ascending=True)
    
    # We drop duplicates based on title and neighborhood, keeping the last (most recent)
    df = df.drop_duplicates(subset=["title", "neighborhood"], keep="last")
    return df

def handle_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """
    Drop rows missing the target variable (rent_eur).
    Impute missing categorical data (e.g., neighborhood) with an 'Unknown' placeholder.
    """
    # Drop rows missing the target variable
    if "monthly_rent_eur" in df.columns:
        df = df.dropna(subset=["monthly_rent_eur"])
    
    # Impute missing categorical data
    if "neighborhood" in df.columns:
        df["neighborhood"] = df["neighborhood"].fillna("Unknown")
        
    return df

def remove_outliers(df: pd.DataFrame) -> pd.DataFrame:
    """
    Eliminate extreme statistical anomalies in rent_eur or rooms using the IQR method.
    """
    for col in ["monthly_rent_eur", "rooms"]:
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
            q1 = df[col].quantile(0.25)
            q3 = df[col].quantile(0.75)
            iqr = q3 - q1
            lower_bound = q1 - 1.5 * iqr
            upper_bound = q3 + 1.5 * iqr
            
            # Keep rows that are within bounds or where the value is missing
            df = df[(df[col].isna()) | ((df[col] >= lower_bound) & (df[col] <= upper_bound))]
            
    return df

def clean_listings_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply the full data cleaning pipeline to the listings dataframe.
    """
    if df is None or df.empty:
        return df
        
    df = deduplicate(df)
    df = handle_missing_values(df)
    df = remove_outliers(df)
    
    return df
